const cfg=window.VOTING_CONFIG,$=s=>document.querySelector(s);let token="",boot=null;
$("#appTitle").textContent=cfg.title;const msg=(e,t,c="notice")=>{e.textContent=t;e.className=c};const esc=s=>String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
async function api(p,b){const r=await fetch(cfg.apiBase+p,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(b)}),d=await r.json();if(!r.ok)throw Error(d.message||d.error);return d}
async function load(){boot=await api("/api/bootstrap",{token});$("#login").classList.add("hidden");$("#member").classList.remove("hidden");$("#memberName").textContent=boot.member.display_name;$("#phaseBadge").textContent=boot.phase;["nominationView","votingView","closedView"].forEach(x=>$("#"+x).classList.add("hidden"));if(boot.phase==="NOMINATION"){$("#nominationView").classList.remove("hidden");renderNom()}if(boot.phase==="VOTING"){ $("#votingView").classList.remove("hidden");await renderVote()}if(boot.phase==="CLOSED")$("#closedView").classList.remove("hidden")}
$("#enterBtn").onclick=async()=>{token=$("#token").value.trim();try{await load()}catch(e){msg($("#loginMsg"),e.message,"error")}};
function renderNom(){$("#nominationIntro").innerHTML=`Choose where <b>${esc(boot.member.display_name)}</b> should appear as a candidate.`;$("#nominationPositions").innerHTML=boot.positions.map(p=>`<div class="position"><label class="option"><input type="checkbox" value="${p.id}" ${boot.myNominations.includes(p.id)?"checked":""}><span><b>${esc(p.title)}</b><br><span class="muted small">${esc(p.description)}</span></span></label></div>`).join("")}
$("#saveNomination").onclick=async()=>{const ids=[...$("#nominationPositions").querySelectorAll("input:checked")].map(x=>x.value);try{await api("/api/submit-nomination",{token,position_ids:ids});msg($("#nominationMsg"),ids.length?`Saved for ${ids.length} position(s).`:"Saved. Your name will not appear for any position.","success")}catch(e){msg($("#nominationMsg"),e.message,"error")}};
async function renderVote(){const c=await api("/api/candidates",{token}),n=await api("/api/association-names",{token});boot.associationNames=n.names;renderNames();$("#addNameBox").classList.toggle("hidden",!boot.allowNameSuggestions);$("#candidateVotes").innerHTML=c.positions.map(p=>`<div class="question"><h3>${esc(p.title)}</h3><p class="muted small">${esc(p.description)}</p>${p.candidates.map(n=>`<label class="option"><input type="radio" name="p_${p.id}" value="${esc(n)}"><span>${esc(n)}</span></label>`).join("")}${!p.candidates.length?"<p class='warning'>No confirmed candidate yet.</p>":""}<label class="option"><input type="radio" name="p_${p.id}" value="Abstain"><span>Abstain / امتنع</span></label></div>`).join("")}
function renderNames(sel=""){$("#associationChoices").innerHTML=boot.associationNames.map(n=>`<label class="option"><input type="radio" name="association_name" value="${esc(n.name)}" ${sel===n.name?"checked":""}><span>${esc(n.name)}</span></label>`).join("")}
$("#addAssociationName").onclick=async()=>{try{const d=await api("/api/add-association-name",{token,name:$("#newAssociationName").value});boot.associationNames=(await api("/api/association-names",{token})).names;renderNames(d.name.name);$("#newAssociationName").value="";msg($("#addNameMsg"),d.message,"success")}catch(e){msg($("#addNameMsg"),e.message,"error")}};
$("#submitVote").onclick=async()=>{const a=$('input[name="association_name"]:checked');if(!a)return msg($("#voteMsg"),"Choose an association name.","error");const positions={};for(const p of boot.positions){const x=$(`input[name="p_${CSS.escape(p.id)}"]:checked`);if(!x)return msg($("#voteMsg"),`Choose for ${p.title}.`,"error");positions[p.id]=x.value}if(!$("#finalConfirm").checked)return msg($("#voteMsg"),"Confirm your final selections.","error");$("#submitVote").disabled=true;try{await api("/api/vote",{token,ballot:{association_name:a.value,positions}});$("#votingView").classList.add("hidden");$("#doneView").classList.remove("hidden")}catch(e){msg($("#voteMsg"),e.message,"error");$("#submitVote").disabled=false}};
